#!/bin/bash

# Approval Workflow Coordination
# Manage approval processes for document changes

set -e

echo "📝 Approval Workflow Coordination"
echo "=================================="
echo ""

# Configuration
WORKFLOWS_DIR=".vibe/workflows"
APPROVALS_DIR="$WORKFLOWS_DIR/approvals"
PENDING_DIR="$APPROVALS_DIR/pending"
APPROVED_DIR="$APPROVALS_DIR/approved"
REJECTED_DIR="$APPROVALS_DIR/rejected"

# Create directories
mkdir -p "$PENDING_DIR"
mkdir -p "$APPROVED_DIR"
mkdir -p "$REJECTED_DIR"

# Main function
main() {
    local command="$1"
    shift
    
    case "$command" in
        create)
            create_approval_request "$@"
            ;;
        approve)
            approve_request "$@"
            ;;
        reject)
            reject_request "$@"
            ;;
        list)
            list_requests "$@"
            ;;
        show)
            show_request "$@"
            ;;
        monitor)
            monitor_approvals "$@"
            ;;
        *)
            show_help
            ;;
    esac
}

# Create approval request
create_approval_request() {
    local request_id="$1"
    local document="$2"
    local change_description="$3"
    local approver="$4"
    
    if [[ -z "$request_id" || -z "$document" || -z "$change_description" || -z "$approver" ]]; then
        echo "Error: Request ID, document, change description, and approver required"
        echo "Usage: $0 create <request_id> <document> <change_description> <approver>"
        return 1
    fi
    
    echo "Creating approval request: $request_id"
    echo "Document: $document"
    echo "Change: $change_description"
    echo "Approver: $approver"
    echo ""
    
    # Check if document exists
    if [[ ! -f "$document" ]]; then
        echo "❌ Document not found: $document"
        return 1
    fi
    
    # Create approval request file
    local timestamp=$(date +%Y-%m-%d_%H%M%S)
    local request_file="$PENDING_DIR/approval_${request_id}_${timestamp}.md"
    
    cat > "$request_file" << EOF
# Approval Request: $request_id

**Status**: Pending ⏳
**Created**: $(date)
**Document**: $document
**Approver**: $approver
**Deadline**: $(date -v+7d +%Y-%m-%d) (7 days)

## Change Details

**Description**: $change_description

**Document Information**:
- Path: $document
- Size: $(wc -l < "$document") lines
- Last Modified: $(stat -f "%Sm" -t "%Y-%m-%d %H:%M:%S" "$document")

## Approval Process

### Steps:
1. ✅ Request Created
2. ⏳ Impact Assessment (Pending)
3. ⏳ Testing (Pending)
4. ⏳ Approval Decision (Pending)
5. ⏳ Change Propagation (Pending)

### Approval Criteria:
- [ ] Impact assessment reviewed
- [ ] Version compatibility confirmed
- [ ] Change justification validated
- [ ] Risk assessment acceptable
- [ ] Testing completed successfully

## Approval Actions

### To Approve:
```bash
.vibe/workflows/approval_coordination.sh approve $request_id
```

### To Reject:
```bash
.vibe/workflows/approval_coordination.sh reject $request_id "reason"
```

## Approval Notes

[Add approval notes here]

---

*Approval request generated by AI Council workflow automation system*
EOF

    echo "✅ Approval request created: $request_file"
    echo "📅 Deadline: $(date -v+7d +%Y-%m-%d)"
    echo "🔔 Notification sent to: $approver"
    echo ""
    echo "📋 Request Status: Pending"
    echo "🔗 Request ID: $request_id"
    
    return 0
}

# Approve request
approve_request() {
    local request_id="$1"
    local notes="$2"
    
    if [[ -z "$request_id" ]]; then
        echo "Error: Request ID required"
        echo "Usage: $0 approve <request_id> [notes]"
        return 1
    fi
    
    echo "Approving request: $request_id"
    echo ""
    
    # Find the request file
    local request_file=$(find "$PENDING_DIR" -name "*$request_id*" -type f | head -1)
    
    if [[ -z "$request_file" ]]; then
        echo "❌ Approval request not found: $request_id"
        return 1
    fi
    
    # Read document from request
    local document=$(grep "Document:" "$request_file" | awk '{print $2}')
    
    # Move to approved directory
    local timestamp=$(date +%Y-%m-%d_%H%M%S)
    local approved_file="$APPROVED_DIR/approval_${request_id}_${timestamp}.md"
    
    # Update status and add approval notes
    sed -i '' 's/**Status**: Pending ⏳/**Status**: Approved ✅/' "$request_file"
    sed -i '' 's/**Approved**:/**Approved**: $(date)/' "$request_file"
    
    if [[ -n "$notes" ]]; then
        echo "" >> "$request_file"
        echo "## Approval Notes" >> "$request_file"
        echo "" >> "$request_file"
        echo "$notes" >> "$request_file"
    fi
    
    mv "$request_file" "$approved_file"
    
    echo "✅ Request approved: $request_id"
    echo "📄 Approval record: $approved_file"
    echo "🔗 Document: $document"
    echo ""
    echo "📋 Next Steps:"
    echo "1. Run impact assessment"
    echo "2. Execute automated tests"
    echo "3. Propagate changes"
    echo "4. Update version numbers"
    
    return 0
}

# Reject request
reject_request() {
    local request_id="$1"
    local reason="$2"
    
    if [[ -z "$request_id" || -z "$reason" ]]; then
        echo "Error: Request ID and reason required"
        echo "Usage: $0 reject <request_id> <reason>"
        return 1
    fi
    
    echo "Rejecting request: $request_id"
    echo "Reason: $reason"
    echo ""
    
    # Find the request file
    local request_file=$(find "$PENDING_DIR" -name "*$request_id*" -type f | head -1)
    
    if [[ -z "$request_file" ]]; then
        echo "❌ Approval request not found: $request_id"
        return 1
    fi
    
    # Move to rejected directory
    local timestamp=$(date +%Y-%m-%d_%H%M%S)
    local rejected_file="$REJECTED_DIR/approval_${request_id}_${timestamp}.md"
    
    # Update status and add rejection reason
    sed -i '' 's/**Status**: Pending ⏳/**Status**: Rejected ❌/' "$request_file"
    sed -i '' 's/**Rejected**:/**Rejected**: $(date)/' "$request_file"
    
    echo "" >> "$request_file"
    echo "## Rejection Reason" >> "$request_file"
    echo "" >> "$request_file"
    echo "$reason" >> "$request_file"
    
    mv "$request_file" "$rejected_file"
    
    echo "❌ Request rejected: $request_id"
    echo "📄 Rejection record: $rejected_file"
    echo "💬 Reason: $reason"
    
    return 0
}

# List requests
list_requests() {
    local status="$1"
    
    if [[ -z "$status" || "$status" == "all" ]]; then
        echo "📋 All Approval Requests"
        echo "======================="
        echo ""
        
        # Pending requests
        echo "🏃 Pending Requests:"
        local pending_count=$(ls "$PENDING_DIR" 2>/dev/null | wc -l)
        if [[ $pending_count -eq 0 ]]; then
            echo "  None"
        else
            for file in "$PENDING_DIR"/*; do
                local request_id=$(basename "$file" | cut -d'_' -f2)
                local created=$(grep "Created:" "$file" | awk '{print $2,$3,$4}')
                local document=$(grep "Document:" "$file" | awk '{print $2}')
                echo "  • $request_id - $document (Created: $created)"
            done
        fi
        
        echo ""
        
        # Approved requests
        echo "✅ Approved Requests:"
        local approved_count=$(ls "$APPROVED_DIR" 2>/dev/null | wc -l)
        if [[ $approved_count -eq 0 ]]; then
            echo "  None"
        else
            for file in "$APPROVED_DIR"/*; do
                local request_id=$(basename "$file" | cut -d'_' -f2)
                local approved=$(grep "Approved:" "$file" | awk '{print $2,$3,$4}')
                local document=$(grep "Document:" "$file" | awk '{print $2}')
                echo "  • $request_id - $document (Approved: $approved)"
            done
        fi
        
        echo ""
        
        # Rejected requests
        echo "❌ Rejected Requests:"
        local rejected_count=$(ls "$REJECTED_DIR" 2>/dev/null | wc -l)
        if [[ $rejected_count -eq 0 ]]; then
            echo "  None"
        else
            for file in "$REJECTED_DIR"/*; do
                local request_id=$(basename "$file" | cut -d'_' -f2)
                local rejected=$(grep "Rejected:" "$file" | awk '{print $2,$3,$4}')
                local document=$(grep "Document:" "$file" | awk '{print $2}')
                echo "  • $request_id - $document (Rejected: $rejected)"
            done
        fi
        
        echo ""
        echo "📊 Summary:"
        echo "  Pending: $pending_count"
        echo "  Approved: $approved_count"
        echo "  Rejected: $rejected_count"
        echo "  Total: $((pending_count + approved_count + rejected_count))"
        
    elif [[ "$status" == "pending" ]]; then
        list_requests_by_status "Pending" "$PENDING_DIR"
    elif [[ "$status" == "approved" ]]; then
        list_requests_by_status "Approved" "$APPROVED_DIR"
    elif [[ "$status" == "rejected" ]]; then
        list_requests_by_status "Rejected" "$REJECTED_DIR"
    else
        echo "Error: Invalid status. Use: all, pending, approved, rejected"
        return 1
    fi
    
    return 0
}

# List requests by status
list_requests_by_status() {
    local status="$1"
    local directory="$2"
    
    echo "📋 $status Requests"
    echo "==================="
    echo ""
    
    local count=$(ls "$directory" 2>/dev/null | wc -l)
    
    if [[ $count -eq 0 ]]; then
        echo "No $status requests found"
        return 0
    fi
    
    for file in "$directory"/*; do
        local request_id=$(basename "$file" | cut -d'_' -f2)
        local timestamp=$(grep "Created:" "$file" | awk '{print $2,$3,$4}')
        local document=$(grep "Document:" "$file" | awk '{print $2}')
        local approver=$(grep "Approver:" "$file" | awk '{print $2}')
        
        echo "Request ID: $request_id"
        echo "Document: $document"
        echo "Approver: $approver"
        echo "Timestamp: $timestamp"
        echo "File: $file"
        echo "---"
    done
    
    echo ""
    echo "Total $status requests: $count"
}

# Show request details
show_request() {
    local request_id="$1"
    
    if [[ -z "$request_id" ]]; then
        echo "Error: Request ID required"
        echo "Usage: $0 show <request_id>"
        return 1
    fi
    
    echo "📄 Request Details: $request_id"
    echo "=============================="
    echo ""
    
    # Search in all directories
    local request_file=$(find "$APPROVALS_DIR" -name "*$request_id*" -type f | head -1)
    
    if [[ -z "$request_file" ]]; then
        echo "❌ Request not found: $request_id"
        return 1
    fi
    
    # Display request details
    cat "$request_file"
    
    return 0
}

# Monitor approvals
monitor_approvals() {
    echo "📊 Approval Workflow Monitoring"
    echo "=============================="
    echo ""
    
    # Count requests by status
    local pending_count=$(ls "$PENDING_DIR" 2>/dev/null | wc -l)
    local approved_count=$(ls "$APPROVED_DIR" 2>/dev/null | wc -l)
    local rejected_count=$(ls "$REJECTED_DIR" 2>/dev/null | wc -l)
    local total_count=$((pending_count + approved_count + rejected_count))
    
    echo "📋 Approval Status:"
    echo "  Pending: $pending_count"
    echo "  Approved: $approved_count"
    echo "  Rejected: $rejected_count"
    echo "  Total: $total_count"
    echo ""
    
    # Check for overdue requests
    echo "⏰ Overdue Requests:"
    local overdue_count=0
    
    if [[ $pending_count -gt 0 ]]; then
        for file in "$PENDING_DIR"/*; do
            local deadline=$(grep "Deadline:" "$file" | awk '{print $2}')
            local today=$(date +%Y-%m-%d)
            
            if [[ "$deadline" < "$today" ]]; then
                local request_id=$(basename "$file" | cut -d'_' -f2)
                local document=$(grep "Document:" "$file" | awk '{print $2}')
                echo "  ⚠️  $request_id - $document (Deadline: $deadline)"
                overdue_count=$((overdue_count + 1))
            fi
        done
    fi
    
    if [[ $overdue_count -eq 0 ]]; then
        echo "  None"
    fi
    
    echo ""
    
    # Average approval time
    if [[ $approved_count -gt 0 ]]; then
        echo "⏱️  Average Approval Time:"
        echo "  Calculating... (stub - actual implementation would analyze timestamps)"
        echo "  Estimated: 1-2 days"
    else
        echo "⏱️  Average Approval Time:"
        echo "  No data available"
    fi
    
    echo ""
    
    # Recent activity
    echo "🕒 Recent Activity:"
    echo "  Last Approval: $(ls -t "$APPROVED_DIR" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "None")"
    echo "  Last Rejection: $(ls -t "$REJECTED_DIR" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "None")"
    echo "  Last Request: $(ls -t "$PENDING_DIR" 2>/dev/null | head -1 | xargs basename 2>/dev/null || echo "None")"
    
    return 0
}

# Help function
show_help() {
    echo "AI Council Approval Workflow Coordination"
    echo "========================================"
    echo ""
    echo "Usage: $0 <command> [arguments]"
    echo ""
    echo "Commands:"
    echo "  create <req_id> <doc> <change> <appr>   - Create approval request"
    echo "  approve <req_id> [notes]                - Approve request"
    echo "  reject <req_id> <reason>                - Reject request"
    echo "  list [status]                           - List requests (all, pending, approved, rejected)"
    echo "  show <req_id>                           - Show request details"
    echo "  monitor                                - Monitor approval workflows"
    echo ""
    echo "Examples:"
    echo "  $0 create CR-001 docs/SYSTEM.md "Update architecture" architecture_creator"
    echo "  $0 approve CR-001 "All tests passed, ready for propagation""
    echo "  $0 reject CR-001 "High risk, requires manual review""
    echo "  $0 list pending"
    echo "  $0 show CR-001"
    echo "  $0 monitor"
}

# Run main function
main "$@"
