#!/bin/bash

# Version Update Automation
# Automate semantic version updates across documents

set -e

echo "📈 Version Update Automation"
echo "============================"
echo ""

# Configuration
WORKFLOWS_DIR=".vibe/workflows"
VERSIONS_DIR="$WORKFLOWS_DIR/versions"
DOCS_DIR="docs"
SKILLS_DIR=".vibe/skills"

# Create versions directory
mkdir -p "$VERSIONS_DIR"

# Main function
main() {
    local command="$1"
    shift
    
    case "$command" in
        update)
            update_version "$@"
            ;;
        bump)
            bump_version "$@"
            ;;
        list)
            list_versions "$@"
            ;;
        history)
            version_history "$@"
            ;;
        *)
            show_help
            ;;
    esac
}

# Update version
update_version() {
    local document="$1"
    local new_version="$2"
    
    if [[ -z "$document" || -z "$new_version" ]]; then
        echo "Error: Document and new version required"
        echo "Usage: $0 update <document> <new_version>"
        return 1
    fi
    
    echo "Updating version for: $document"
    echo "New Version: $new_version"
    echo ""
    
    # Check if document exists
    if [[ ! -f "$document" ]]; then
        echo "❌ Document not found: $document"
        return 1
    fi
    
    # Validate version format
    if ! validate_version "$new_version"; then
        echo "❌ Invalid version format: $new_version"
        echo "Valid format: X.Y.Z (e.g., 1.0.0)"
        return 1
    fi
    
    # Extract current version
    local current_version=$(extract_version "$document")
    
    if [[ -z "$current_version" ]]; then
        echo "❌ No version information found in document"
        return 1
    fi
    
    echo "Current Version: $current_version"
    
    # Compare versions
    local comparison=$(compare_versions "$current_version" "$new_version")
    
    if [[ "$comparison" == "equal" ]]; then
        echo "⚠️  New version same as current version"
        return 0
    elif [[ "$comparison" == "greater" ]]; then
        echo "❌ New version is older than current version"
        return 1
    fi
    
    # Determine version type
    local version_type=$(determine_version_type "$current_version" "$new_version")
    
    echo "Version Type: $version_type"
    
    # Create version update record
    local timestamp=$(date +%Y-%m-%d_%H%M%S)
    local update_record="$VERSIONS_DIR/update_${timestamp}.md"
    
    cat > "$update_record" << EOF
# Version Update: $document

**Status**: Pending ⏳
**Document**: $document
**Current Version**: $current_version
**New Version**: $new_version
**Update Type**: $version_type
**Timestamp**: $(date)

## Version Details

### Version Comparison
- Current: $current_version
- New: $new_version
- Type: $version_type
- Change: $current_version → $new_version

### Semantic Versioning
- **Major**: $(echo "$new_version" | cut -d'.' -f1)
- **Minor**: $(echo "$new_version" | cut -d'.' -f2)
- **Patch**: $(echo "$new_version" | cut -d'.' -f3)

## Update Process

### Pre-Update Checklist
- [ ] Verify approval status
- [ ] Confirm impact assessment completed
- [ ] Validate testing results
- [ ] Backup current document
- [ ] Notify affected systems

### Update Execution
- [ ] Update version in document
- [ ] Modify version references
- [ ] Update dependency versions
- [ ] Validate version format
- [ ] Confirm version compatibility

### Post-Update Checklist
- [ ] Verify version update applied
- [ ] Confirm system functionality
- [ ] Update documentation
- [ ] Notify stakeholders
- [ ] Archive update records

## Update Commands

To apply this update:
```bash
.vibe/workflows/version_updates.sh bump $document $version_type
```

---

*Version update record generated by AI Council workflow automation system*
EOF

    echo "✅ Version update planned"
    echo "📄 Update record: $update_record"
    echo ""
    echo "📋 Next Steps:"
    echo "1. Review version update"
    echo "2. Execute automated tests"
    echo "3. Apply version update"
    echo "4. Verify update success"
    
    return 0
}

# Bump version
bump_version() {
    local document="$1"
    local version_type="$2"  # patch, minor, major
    
    if [[ -z "$document" || -z "$version_type" ]]; then
        echo "Error: Document and version type required"
        echo "Usage: $0 bump <document> <version_type>"
        echo "Version types: patch, minor, major"
        return 1
    fi
    
    echo "Bumping version for: $document"
    echo "Version Type: $version_type"
    echo ""
    
    # Check if document exists
    if [[ ! -f "$document" ]]; then
        echo "❌ Document not found: $document"
        return 1
    fi
    
    # Extract current version
    local current_version=$(extract_version "$document")
    
    if [[ -z "$current_version" ]]; then
        echo "❌ No version information found in document"
        return 1
    fi
    
    echo "Current Version: $current_version"
    
    # Calculate new version
    local new_version=$(calculate_new_version "$current_version" "$version_type")
    
    echo "New Version: $new_version"
    
    # Create version bump record
    local timestamp=$(date +%Y-%m-%d_%H%M%S)
    local bump_record="$VERSIONS_DIR/bump_${timestamp}.md"
    
    cat > "$bump_record" << EOF
# Version Bump: $document

**Status**: Completed ✅
**Document**: $document
**Current Version**: $current_version
**New Version**: $new_version
**Bump Type**: $version_type
**Timestamp**: $(date)

## Version Bump Details

### Version Information
- **Document**: $document
- **Current Version**: $current_version
- **New Version**: $new_version
- **Bump Type**: $version_type

### Semantic Versioning
- **Major**: $(echo "$new_version" | cut -d'.' -f1)
- **Minor**: $(echo "$new_version" | cut -d'.' -f2)
- **Patch**: $(echo "$new_version" | cut -d'.' -f3)

### Version Changes
- **Major Change**: $(echo "$new_version" | cut -d'.' -f1) → $(echo "$current_version" | cut -d'.' -f1)
- **Minor Change**: $(echo "$new_version" | cut -d'.' -f2) → $(echo "$current_version" | cut -d'.' -f2)
- **Patch Change**: $(echo "$new_version" | cut -d'.' -f3) → $(echo "$current_version" | cut -d'.' -f3)

## Bump Process

### Pre-Bump Checklist
- [x] Verify document exists
- [x] Extract current version
- [x] Validate version format
- [x] Calculate new version
- [x] Create bump record

### Bump Execution
- [x] Calculate version bump
- [x] Create version record
- [x] Document version change
- [x] Generate changelog entry

### Post-Bump Checklist
- [ ] Apply version update to document
- [ ] Update version references
- [ ] Modify dependency versions
- [ ] Validate version format
- [ ] Confirm version compatibility

## Version Metadata

- **Bump ID**: $(basename "$bump_record" .md)
- **Document**: $document
- **Bump Type**: $version_type
- **Current Version**: $current_version
- **New Version**: $new_version
- **Timestamp**: $(date)

---

*Version bump record generated by AI Council workflow automation system*
EOF

    echo "✅ Version bump calculated"
    echo "📄 Bump record: $bump_record"
    echo ""
    echo "📋 Version Change:"
    echo "  $current_version → $new_version ($version_type)"
    
    return 0
}

# List versions
list_versions() {
    echo "📋 Version Update History"
    echo "========================="
    echo ""
    
    # Count version files
    local update_count=$(ls "$VERSIONS_DIR" 2>/dev/null | grep "update_" | wc -l)
    local bump_count=$(ls "$VERSIONS_DIR" 2>/dev/null | grep "bump_" | wc -l)
    local total_count=$((update_count + bump_count))
    
    echo "Version Records:"
    echo "  Updates: $update_count"
    echo "  Bumps: $bump_count"
    echo "  Total: $total_count"
    echo ""
    
    if [[ $total_count -eq 0 ]]; then
        echo "No version records found"
        return 0
    fi
    
    echo "Recent Version Updates:"
    
    # Show recent update files
    for file in $(ls -t "$VERSIONS_DIR"/update_* 2>/dev/null | head -5); do
        local doc=$(grep "Document:" "$file" | awk '{print $2}')
        local current=$(grep "Current Version:" "$file" | awk '{print $3}')
        local new=$(grep "New Version:" "$file" | awk '{print $3}')
        local type=$(grep "Update Type:" "$file" | awk '{print $3}')
        local timestamp=$(basename "$file" | cut -d'_' -f2)
        
        echo "  • $timestamp: $doc ($current → $new) [$type]"
    done
    
    echo ""
    echo "Recent Version Bumps:"
    
    # Show recent bump files
    for file in $(ls -t "$VERSIONS_DIR"/bump_* 2>/dev/null | head -5); do
        local doc=$(grep "Document:" "$file" | awk '{print $2}')
        local current=$(grep "Current Version:" "$file" | awk '{print $3}')
        local new=$(grep "New Version:" "$file" | awk '{print $3}')
        local type=$(grep "Bump Type:" "$file" | awk '{print $3}')
        local timestamp=$(basename "$file" | cut -d'_' -f2)
        
        echo "  • $timestamp: $doc ($current → $new) [$type]"
    done
    
    return 0
}

# Version history
version_history() {
    local document="$1"
    
    if [[ -z "$document" ]]; then
        echo "Error: Document required"
        echo "Usage: $0 history <document>"
        return 1
    fi
    
    echo "📊 Version History: $document"
    echo "================================"
    echo ""
    
    # Find version files for this document
    local version_files=$(grep -l "Document: $document" "$VERSIONS_DIR"/* 2>/dev/null)
    local count=$(echo "$version_files" | wc -w)
    
    if [[ $count -eq 0 ]]; then
        echo "No version history found for: $document"
        return 0
    fi
    
    echo "Version History ($count records):"
    echo ""
    
    # Extract current version
    local current_version=$(extract_version "$document")
    
    if [[ -n "$current_version" ]]; then
        echo "Current Version: $current_version"
        echo ""
    fi
    
    # Show version history in chronological order
    for file in $(echo "$version_files" | tr ' ' '\n' | sort); do
        local timestamp=$(basename "$file" | cut -d'_' -f2)
        local current=$(grep "Current Version:" "$file" | awk '{print $3}')
        local new=$(grep "New Version:" "$file" | awk '{print $3}')
        local type=$(grep -E "(Update Type|Bump Type):" "$file" | awk '{print $3}')
        local status=$(grep "Status:" "$file" | awk '{print $2}')
        
        echo "$timestamp:"
        echo "  Status: $status"
        echo "  Change: $current → $new"
        echo "  Type: $type"
        echo "  File: $(basename "$file")"
        echo ""
    done
    
    return 0
}

# Extract version from document
extract_version() {
    local document="$1"
    
    if grep -q "version:" "$document"; then
        grep "version:" "$document" | awk '{print $2}' | tr -d '"'
    elif grep -q "Version:" "$document"; then
        grep "Version:" "$document" | awk '{print $2}'
    else
        echo ""
    fi
}

# Validate version format
validate_version() {
    local version="$1"
    
    # Check if version matches X.Y.Z format
    if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        return 0
    else
        return 1
    fi
}

# Compare versions
compare_versions() {
    local v1="$1"
    local v2="$2"
    
    # Convert versions to comparable format
    local v1_major=$(echo "$v1" | cut -d'.' -f1)
    local v1_minor=$(echo "$v1" | cut -d'.' -f2)
    local v1_patch=$(echo "$v1" | cut -d'.' -f3)
    
    local v2_major=$(echo "$v2" | cut -d'.' -f1)
    local v2_minor=$(echo "$v2" | cut -d'.' -f2)
    local v2_patch=$(echo "$v2" | cut -d'.' -f3)
    
    # Compare major versions
    if [[ $v2_major -gt $v1_major ]]; then
        echo "greater"
    elif [[ $v2_major -lt $v1_major ]]; then
        echo "less"
    else
        # Compare minor versions
        if [[ $v2_minor -gt $v1_minor ]]; then
            echo "greater"
        elif [[ $v2_minor -lt $v1_minor ]]; then
            echo "less"
        else
            # Compare patch versions
            if [[ $v2_patch -gt $v1_patch ]]; then
                echo "greater"
            elif [[ $v2_patch -lt $v1_patch ]]; then
                echo "less"
            else
                echo "equal"
            fi
        fi
    fi
}

# Determine version type
determine_version_type() {
    local current="$1"
    local new="$2"
    
    local current_major=$(echo "$current" | cut -d'.' -f1)
    local current_minor=$(echo "$current" | cut -d'.' -f2)
    local current_patch=$(echo "$current" | cut -d'.' -f3)
    
    local new_major=$(echo "$new" | cut -d'.' -f1)
    local new_minor=$(echo "$new" | cut -d'.' -f2)
    local new_patch=$(echo "$new" | cut -d'.' -f3)
    
    if [[ $new_major -gt $current_major ]]; then
        echo "major"
    elif [[ $new_minor -gt $current_minor ]]; then
        echo "minor"
    elif [[ $new_patch -gt $current_patch ]]; then
        echo "patch"
    else
        echo "unknown"
    fi
}

# Calculate new version
calculate_new_version() {
    local current="$1"
    local version_type="$2"
    
    local major=$(echo "$current" | cut -d'.' -f1)
    local minor=$(echo "$current" | cut -d'.' -f2)
    local patch=$(echo "$current" | cut -d'.' -f3)
    
    case "$version_type" in
        patch)
            echo "$major.$minor.$((patch + 1))"
            ;;
        minor)
            echo "$major.$((minor + 1)).0"
            ;;
        major)
            echo "$((major + 1)).0.0"
            ;;
        *)
            echo "$current"
            ;;
    esac
}

# Help function
show_help() {
    echo "AI Council Version Update Automation"
    echo "====================================="
    echo ""
    echo "Usage: $0 <command> [arguments]"
    echo ""
    echo "Commands:"
    echo "  update <doc> <new_version>          - Update to specific version"
    echo "  bump <doc> <type>                   - Bump version (patch, minor, major)"
    echo "  list                                - List version updates"
    echo "  history <doc>                       - Show version history for document"
    echo ""
    echo "Examples:"
    echo "  $0 update docs/SYSTEM.md 2.0.0"
    echo "  $0 bump .vibe/skills/test_skill/SKILL.md patch"
    echo "  $0 list"
    echo "  $0 history docs/SYSTEM.md"
}

# Run main function
main "$@"
